/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

/**
 *
 * @author Luis
 */
import EstructurasDeDatos.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Clases.*;
import java.io.IOException;

public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    private Arbol arbol;
    private Nodo actual;
    public static Ventana1 v1;

    public Ventana2() {
        initComponents();

        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        //setResizable(false); // Impide cambiar la dimension de la ventana
        setTitle("Clave Dicotómica");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // Crear el árbol y la interfaz
        try {
            Arbol arbol = CargadorJSON.cargarArbol("arboles_templados.json");
            arbol.mostrarArbol();
            this.arbol = arbol;
            if (arbol.getRaiz() == null) {
                throw new IllegalStateException("El árbol no tiene una raíz válida.");
            }
            this.actual = arbol.getRaiz();
            PreguntasTexto.setText(actual.pregunta);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar el archivo JSON: " + e.getMessage());
        }

        PanelDerecha.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIzquierda = new javax.swing.JPanel();
        BotonSi = new javax.swing.JButton();
        BotonNo = new javax.swing.JButton();
        PreguntasTexto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PanelDerecha = new javax.swing.JPanel();
        InformacionPlantas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotonBuscarArbol = new javax.swing.JButton();
        BotonBuscarHash = new javax.swing.JButton();
        BuscarNombrePlanta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        MenuCargarArchivo = new javax.swing.JMenuItem();
        MenuMostrarArbol = new javax.swing.JMenuItem();
        MenuReiniciar = new javax.swing.JMenuItem();
        MenuBuscar = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        MenuIntegrantes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzquierda.setBackground(new java.awt.Color(246, 229, 229));
        PanelIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSi.setBackground(new java.awt.Color(102, 51, 0));
        BotonSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonSi.setForeground(new java.awt.Color(255, 255, 255));
        BotonSi.setText("SI");
        BotonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 80, 40));

        BotonNo.setBackground(new java.awt.Color(102, 51, 0));
        BotonNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonNo.setForeground(new java.awt.Color(255, 255, 255));
        BotonNo.setText("NO");
        BotonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNoActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 80, 40));

        PreguntasTexto.setBackground(new java.awt.Color(173, 205, 173));
        PreguntasTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PreguntasTexto.setForeground(new java.awt.Color(0, 0, 0));
        PreguntasTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PreguntasTexto.setFocusable(false);
        PanelIzquierda.add(PreguntasTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 480, 120));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("Clave Dicotómica");
        jLabel8.setToolTipText("");
        PanelIzquierda.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        getContentPane().add(PanelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 320));

        PanelDerecha.setBackground(new java.awt.Color(246, 229, 229));
        PanelDerecha.setForeground(new java.awt.Color(0, 0, 0));
        PanelDerecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InformacionPlantas.setBackground(new java.awt.Color(173, 205, 173));
        InformacionPlantas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InformacionPlantas.setForeground(new java.awt.Color(0, 0, 0));
        InformacionPlantas.setFocusable(false);
        InformacionPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionPlantasActionPerformed(evt);
            }
        });
        PanelDerecha.add(InformacionPlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 340, 140));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Información de la especie:");
        PanelDerecha.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        BotonBuscarArbol.setBackground(new java.awt.Color(102, 51, 0));
        BotonBuscarArbol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonBuscarArbol.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscarArbol.setText("Árbol");
        BotonBuscarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarArbolActionPerformed(evt);
            }
        });
        PanelDerecha.add(BotonBuscarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 90, -1));

        BotonBuscarHash.setBackground(new java.awt.Color(102, 51, 0));
        BotonBuscarHash.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonBuscarHash.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscarHash.setText("Hash");
        BotonBuscarHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarHashActionPerformed(evt);
            }
        });
        PanelDerecha.add(BotonBuscarHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 90, -1));

        BuscarNombrePlanta.setBackground(new java.awt.Color(173, 205, 173));
        BuscarNombrePlanta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BuscarNombrePlanta.setForeground(new java.awt.Color(0, 0, 0));
        PanelDerecha.add(BuscarNombrePlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("Buscar por nombre de la especie:");
        PanelDerecha.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setText("Tiempo para encontrar la información: ");
        PanelDerecha.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Tiempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tiempo.setForeground(new java.awt.Color(51, 102, 0));
        Tiempo.setText("15");
        PanelDerecha.add(Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 70, -1));

        getContentPane().add(PanelDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 320));

        jMenuBar1.setBackground(new java.awt.Color(246, 229, 229));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        MenuOpciones.setText("Opciones");
        MenuOpciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuCargarArchivo.setText("Cargar Archivo");
        MenuCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCargarArchivoActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuCargarArchivo);

        MenuMostrarArbol.setText("Mostrar Arbol");
        MenuMostrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMostrarArbolActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuMostrarArbol);

        MenuReiniciar.setText("Reiniciar");
        MenuReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReiniciarActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuReiniciar);

        MenuBuscar.setText("Buscar");
        MenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscarActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuBuscar);

        jMenuBar1.add(MenuOpciones);

        MenuAyuda.setText("Ayuda");
        MenuAyuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MenuIntegrantes.setText("Integrantes");
        MenuAyuda.add(MenuIntegrantes);

        jMenuBar1.add(MenuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguientePregunta(boolean respuesta) {
        // Verificar si actual es null
        if (actual == null) {
            JOptionPane.showMessageDialog(this, "Error: No se ha cargado correctamente el árbol.");
            return;
        }

        // Verificar si ya se ha encontrado la especie
        if (actual.especie != null) {
            JOptionPane.showMessageDialog(this, "Ya se ha encontrado la especie: " + actual.especie + "\nNo se pueden realizar más preguntas.");
            return; // Salir del método sin hacer nada más
        }

        // Mover al siguiente nodo según la respuesta
        if (respuesta) {
            actual = actual.si;
        } else {
            actual = actual.no;
        }

        // Verificar si el nuevo nodo es null
        if (actual == null) {
            JOptionPane.showMessageDialog(this, "Error: No hay más preguntas disponibles.");
            return;
        }

        // Verificar si el nuevo nodo es una hoja (especie)
        if (actual.especie != null) {
            JOptionPane.showMessageDialog(this, "La especie es: " + actual.especie);
        } else {
            // Actualizar la pregunta en la interfaz
            PreguntasTexto.setText(actual.pregunta);
        }
    }

    private void cargarNuevaClave() {
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try {
                arbol = CargadorJSON.cargarArbol(archivo.getAbsolutePath());
                actual = arbol.getRaiz();
                PreguntasTexto.setText(actual.pregunta);
                JOptionPane.showMessageDialog(this, "Nueva clave cargada correctamente.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar el archivo: " + e.getMessage());
            }
        }
    }

    private void reiniciarBusqueda() {
        // Volver a la raíz del árbol
        actual = arbol.getRaiz();
        PreguntasTexto.setText(actual.pregunta);
        JOptionPane.showMessageDialog(this, "Búsqueda reiniciada. Comienza desde la primera pregunta.");
    }
    private void BotonBuscarHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarHashActionPerformed


    }//GEN-LAST:event_BotonBuscarHashActionPerformed

    private void InformacionPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionPlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InformacionPlantasActionPerformed

    private void BotonBuscarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarArbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarArbolActionPerformed

    private void BotonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiActionPerformed
        siguientePregunta(true);
    }//GEN-LAST:event_BotonSiActionPerformed

    private void BotonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNoActionPerformed
        siguientePregunta(false);
    }//GEN-LAST:event_BotonNoActionPerformed

    private void MenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarActionPerformed
        PanelDerecha.setVisible(true);
        PanelIzquierda.setVisible(false);
    }//GEN-LAST:event_MenuBuscarActionPerformed

    private void MenuCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCargarArchivoActionPerformed
        cargarNuevaClave();
    }//GEN-LAST:event_MenuCargarArchivoActionPerformed

    private void MenuMostrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMostrarArbolActionPerformed
        VisualizadorArbol visualizador = new VisualizadorArbol();
        visualizador.mostrarArbol(arbol.getRaiz());
    }//GEN-LAST:event_MenuMostrarArbolActionPerformed

    private void MenuReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReiniciarActionPerformed
        reiniciarBusqueda();
    }//GEN-LAST:event_MenuReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarArbol;
    private javax.swing.JButton BotonBuscarHash;
    private javax.swing.JButton BotonNo;
    private javax.swing.JButton BotonSi;
    private javax.swing.JTextField BuscarNombrePlanta;
    private javax.swing.JTextField InformacionPlantas;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenuItem MenuBuscar;
    private javax.swing.JMenuItem MenuCargarArchivo;
    private javax.swing.JMenuItem MenuIntegrantes;
    private javax.swing.JMenuItem MenuMostrarArbol;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JMenuItem MenuReiniciar;
    private javax.swing.JPanel PanelDerecha;
    private javax.swing.JPanel PanelIzquierda;
    private javax.swing.JTextField PreguntasTexto;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
