/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

/**
 *
 * @author Luis
 */
import EstructurasDeDatos.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Clases.*;
import java.io.IOException;

public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    private Arbol arbol;
    private Nodo actual;
    public static Ventana1 v1;

    public Ventana2() {
        initComponents();

        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setResizable(false); // Impide cambiar la dimension de la ventana
        setTitle("Clave Dicotómica");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // Crear el árbol y la interfaz
        try {
            Arbol arbol = CargadorJSON.cargarArbol("arboles_templados.json");
            arbol.mostrarArbol();
            this.arbol = arbol;
            if (arbol.getRaiz() == null) {
                throw new IllegalStateException("El árbol no tiene una raíz válida.");
            }
            this.actual = arbol.getRaiz();
            PreguntasTexto.setText(actual.pregunta);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar el archivo JSON: " + e.getMessage());
        }

        PanelDerecha.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIzquierda = new javax.swing.JPanel();
        BotonSi = new javax.swing.JButton();
        BotonNo = new javax.swing.JButton();
        BotonCargarArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PreguntasTexto = new javax.swing.JTextField();
        BotonMostrarArbol = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotonReiniciar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BotonReiniciar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PanelDerecha = new javax.swing.JPanel();
        InformacionPlantas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotonBuscarArbol = new javax.swing.JButton();
        BotonBuscarHash = new javax.swing.JButton();
        BuscarNombrePlanta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSi.setText("SI");
        BotonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 80, 40));

        BotonNo.setText("NO");
        BotonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNoActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 80, 40));

        BotonCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarArchivoActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonCargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 70, 70));

        jLabel1.setText("Cargar Archivo");
        PanelIzquierda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        PreguntasTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PreguntasTexto.setFocusable(false);
        PanelIzquierda.add(PreguntasTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 480, 120));

        BotonMostrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarArbolActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonMostrarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 70, 70));

        jLabel2.setText("Mostrar Arbol");
        PanelIzquierda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        BotonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReiniciarActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 70, 70));

        jLabel5.setText("Reiniciar");
        PanelIzquierda.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        BotonReiniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReiniciar1ActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonReiniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 70, 70));

        jLabel7.setText("Buscar");
        PanelIzquierda.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jLabel8.setText("Clave Dicotómica");
        PanelIzquierda.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        getContentPane().add(PanelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 550));

        PanelDerecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InformacionPlantas.setFocusable(false);
        InformacionPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionPlantasActionPerformed(evt);
            }
        });
        PanelDerecha.add(InformacionPlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, 340));

        jLabel4.setText("Información de la especie:");
        PanelDerecha.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        BotonBuscarArbol.setText("Árbol");
        BotonBuscarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarArbolActionPerformed(evt);
            }
        });
        PanelDerecha.add(BotonBuscarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 70, -1));

        BotonBuscarHash.setText("Hash");
        BotonBuscarHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarHashActionPerformed(evt);
            }
        });
        PanelDerecha.add(BotonBuscarHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, -1));
        PanelDerecha.add(BuscarNombrePlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, -1));

        jLabel6.setText("Buscar por nombre de la especie:");
        PanelDerecha.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("Tiempo para encontrar la información: ");
        PanelDerecha.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        Tiempo.setText("15");
        PanelDerecha.add(Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 70, -1));

        getContentPane().add(PanelDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 290, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguientePregunta(boolean respuesta) {
        // Verificar si actual es null
        if (actual == null) {
            JOptionPane.showMessageDialog(this, "Error: No se ha cargado correctamente el árbol.");
            return;
        }

        // Verificar si ya se ha encontrado la especie
        if (actual.especie != null) {
            JOptionPane.showMessageDialog(this, "Ya se ha encontrado la especie: " + actual.especie + "\nNo se pueden realizar más preguntas.");
            return; // Salir del método sin hacer nada más
        }

        // Mover al siguiente nodo según la respuesta
        if (respuesta) {
            actual = actual.si;
        } else {
            actual = actual.no;
        }

        // Verificar si el nuevo nodo es null
        if (actual == null) {
            JOptionPane.showMessageDialog(this, "Error: No hay más preguntas disponibles.");
            return;
        }

        // Verificar si el nuevo nodo es una hoja (especie)
        if (actual.especie != null) {
            JOptionPane.showMessageDialog(this, "La especie es: " + actual.especie);
        } else {
            // Actualizar la pregunta en la interfaz
            PreguntasTexto.setText(actual.pregunta);
        }
    }

    private void cargarNuevaClave() {
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try {
                arbol = CargadorJSON.cargarArbol(archivo.getAbsolutePath());
                actual = arbol.getRaiz();
                PreguntasTexto.setText(actual.pregunta);
                JOptionPane.showMessageDialog(this, "Nueva clave cargada correctamente.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar el archivo: " + e.getMessage());
            }
        }
    }

    private void reiniciarBusqueda() {
        // Volver a la raíz del árbol
        actual = arbol.getRaiz();
        PreguntasTexto.setText(actual.pregunta);
        JOptionPane.showMessageDialog(this, "Búsqueda reiniciada. Comienza desde la primera pregunta.");
    }
    private void BotonBuscarHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarHashActionPerformed


    }//GEN-LAST:event_BotonBuscarHashActionPerformed

    private void InformacionPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionPlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InformacionPlantasActionPerformed

    private void BotonBuscarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarArbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarArbolActionPerformed

    private void BotonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiActionPerformed
        siguientePregunta(true);
    }//GEN-LAST:event_BotonSiActionPerformed

    private void BotonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNoActionPerformed
        siguientePregunta(false);
    }//GEN-LAST:event_BotonNoActionPerformed

    private void BotonMostrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarArbolActionPerformed
        VisualizadorArbol visualizador = new VisualizadorArbol();
        visualizador.mostrarArbol(arbol.getRaiz());
    }//GEN-LAST:event_BotonMostrarArbolActionPerformed

    private void BotonCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarArchivoActionPerformed
        cargarNuevaClave();
    }//GEN-LAST:event_BotonCargarArchivoActionPerformed

    private void BotonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReiniciarActionPerformed
        reiniciarBusqueda();
    }//GEN-LAST:event_BotonReiniciarActionPerformed

    private void BotonReiniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReiniciar1ActionPerformed
        PanelDerecha.setVisible(true);
        PanelIzquierda.setVisible(false);
    }//GEN-LAST:event_BotonReiniciar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarArbol;
    private javax.swing.JButton BotonBuscarHash;
    private javax.swing.JButton BotonCargarArchivo;
    private javax.swing.JButton BotonMostrarArbol;
    private javax.swing.JButton BotonNo;
    private javax.swing.JButton BotonReiniciar;
    private javax.swing.JButton BotonReiniciar1;
    private javax.swing.JButton BotonSi;
    private javax.swing.JTextField BuscarNombrePlanta;
    private javax.swing.JTextField InformacionPlantas;
    private javax.swing.JPanel PanelDerecha;
    private javax.swing.JPanel PanelIzquierda;
    private javax.swing.JTextField PreguntasTexto;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
